### ISSUE TITLE
docker volumes can't be shared across nodes

### ISSUE THREAD

**Issue by dcalacci** [rifflearning/riff-docker#2]
our nginx configuration breaks when we deploy to a docker cluster. 

Right now we declare a shared volume, `rtc-build`, that is shared between our `riff-rtc` and our `web-server` services. 

When we deploy to a cluster, there's no guarantee right now that these services will be running on the same node. 

To share a volume between services, they must be running on the same node. 

So either:

- we create another service that is a persistent storage volume, through S3 or NFS or something similar
- we somehow ensure in the compose configuration that `riff-rtc` and `web-server` always run on the same node.

In reality, we do not need to build our client-side code from `riff-rtc` in a docker container. The only thing it needs to know is where to send server-side requests (which is broken right now anyway). 

Maybe a third option is to separate our client-side build from our server-side build, and point our server-side code -- nginx or the riff-server -- to an s3 bucket with our webpacked frontend? still the issue of declaring server URLs for front-end requests.

**Comment by adonahue** [comment]
@mlippert and @jordanreedie - can you weigh in on if this is still an issue, and if it is, help me understand how to prioritize it? I don't have enough info to understand what the business impact or urgency is. Thanks!

**Comment by mlippert** [comment]
Well given that the issue was opened June 7, 2018, the urgency is low. :wink: 

So this issue is no longer relevant because we don't attempt to share a volume between the riff-rtc container and the web-server container. Instead the solution to this issue (not the best solution, but it's working) was to prebuild an image from the riff-rtc repo, and then copy the relevant files from that image when building the riff-rtc and web-server containers. So each of those images contains the files it needs from a specific build.
